👷 Add codecov on push commit hook

diff --git a/.githooks/pre-push b/.githooks/pre-push
--- a/.githooks/pre-push
+++ b/.githooks/pre-push
@@ -10,3 +10,9 @@ if [ $? -ne 0 ]; then
   echo >&2 "Test failed"
   exit 1
 fi
+
+make coverage-upload
+if [ $? -ne 0 ]; then
+  echo >&2 "Upload coverage failed"
+  exit 1
+fi
